---
title: "Lab03"
format: html
editor: visual
---

## 1.

```{r}
library(readr)
library(dplyr)

airports = read_csv("airports.csv",
                    col_select = c(IATA_CODE, CITY, STATE, LATITUDE, LONGITUDE))

airlines = read_csv("airlines.csv")

resultado_final = data.frame(
  DESTINATION_AIRPORT = character(),
  soma_atraso = numeric(),
  n_voos = numeric()
)

minha_funcao = function(pedaco, pos) {
  
  pedaco = pedaco[substr(pedaco$DESTINATION_AIRPORT, 1, 1) != "1", ]
  
  pedaco = na.omit(pedaco)
  
  resumo_pedaco = pedaco %>%
    group_by(DESTINATION_AIRPORT) %>%
    summarise(soma_atraso = sum(ARRIVAL_DELAY),
              n_voos = n())
  
  resultado_final <<- rbind(resultado_final, resumo_pedaco)
}

read_csv_chunked(
  "flights.csv",
  col_types = cols_only(DESTINATION_AIRPORT = col_character(),
                        ARRIVAL_DELAY = col_double()),
  chunk_size = 1000000,
  callback = SideEffectChunkCallback$new(minha_funcao)
)

flights = resultado_final %>%
  group_by(DESTINATION_AIRPORT) %>%
  summarise(soma_atraso = sum(soma_atraso),
            n_voos = sum(n_voos)) %>%
  mutate(atraso_medio = soma_atraso / n_voos)
```

## 2.

a-) Chave em flights: DESTINATION_AIRPORT

b-) Chave em airports: IATA_CODE

c-) Não há aeroportos em flights que não estejam em airports

```{r}
flights %>%
  anti_join(airports, by = c("DESTINATION_AIRPORT" = "IATA_CODE"))
```

d-) e e-)

```{r}
flights = flights %>%
  left_join(airports %>% select(IATA_CODE, CITY, STATE),
            by = c("DESTINATION_AIRPORT" = "IATA_CODE"))
```

## 3.

```{r}
airports %>%
  group_by(STATE) %>%
  summarise(n_aeroportos = n()) %>%
  arrange(desc(n_aeroportos))
```

## 4.

```{r}
library(leaflet)

mapa_dados = flights %>%
  left_join(airports %>% select(IATA_CODE, LATITUDE, LONGITUDE),
            by = c("DESTINATION_AIRPORT" = "IATA_CODE"))

this = leaflet(mapa_dados) %>%
  addTiles() %>%
  addMarkers(lng = ~LONGITUDE, lat = ~LATITUDE,
             popup = ~paste(DESTINATION_AIRPORT, "- Atraso médio:", round(atraso_medio, 1)))

this
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
