---
title: "lab06"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)
library(dplyr)
```

## 1.

```{r}
path <- getwd()
fname <- file.path(path, "disco.db")
```

## 2.

```{r}
conn <- dbConnect(RSQLite::SQLite(), fname)
```

## 3.

```{r}
dbListTables(conn)
```

## 4.

```{r}
dbListFields(conn, "customers")
```

## 5.

```{sql, connection=conn}
SELECT COUNT(*) AS total_clientes FROM customers
```

## 6.

```{sql, connection=conn}
SELECT COUNT(DISTINCT Country) AS n_paises FROM customers
```

## 7.

```{sql, connection=conn}
SELECT Country, COUNT(*) AS total_clientes FROM customers
GROUP BY Country
ORDER BY total_clientes DESC
```

## 8.

```{sql, connection=conn}
SELECT Country, COUNT(*) AS total_clientes FROM customers
GROUP BY Country
ORDER BY total_clientes DESC
LIMIT 5
```

## 9.

```{sql, connection=conn}
SELECT DISTINCT(COUNTRY) FROM CUSTOMERS
WHERE COUNTRY LIKE "______"
```

## 10.

```{sql, connection=conn}
SELECT DISTINCT t.Name AS musica
FROM customers AS c
JOIN invoices AS i ON c.CustomerId = i.CustomerId
JOIN invoice_items AS ii ON i.InvoiceId = ii.InvoiceId
JOIN tracks AS t ON ii.TrackId = t.TrackId
WHERE c.Country = 'Brazil'
```

## 11.

```{r}
dbDisconnect(conn)
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
