---
title: "lista05"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)

# Conecta/Cria o arquivo
con <- dbConnect(RSQLite::SQLite(), "me315.sqlite")
```

## 1.

```{sql connection=con}
SELECT PNAME, ACRES, ACRES + ACRES * 20.0/100.0 AS AUMENTO FROM PRESERVE
```

## 2.

```{sql connection=con}
SELECT PNAME, ACRES, ACRES - ACRES * 1.0/3.0 AS AJUSTADO FROM PRESERVE
```

## 3.

```{sql connection=con}
SELECT PNAME, FEE, (FEE+50.0)/2 AS TAXA_AJUSTADA FROM PRESERVE
```

## 4.

```{sql connection=con}
SELECT AVG(ACRES) AS VALOR_MEDIO, MIN(ACRES) AS VALOR_MIN, MAX(ACRES) AS VALOR_MAX FROM PRESERVE
WHERE STATE = 'AZ'
```

## 5.

```{sql connection=con}
SELECT MIN(PNAME) FROM PRESERVE
```

## 6.

```{sql connection=con}
SELECT COUNT(DISTINCT FEE) FROM PRESERVE
WHERE FEE <> 0
```

## 7.

```{sql connection=con}
SELECT COUNT(DISTINCT PNAME) FROM PRESERVE
```

## 8.

```{sql connection=con}
SELECT AVG(ACRES * 0.02) AS TAXA_MEDIA FROM PRESERVE
WHERE STATE = 'AZ'
```

## 9.

```{sql connection=con}
SELECT ENO, ENAME, SALARY AS OLDSALARY, SALARY + SALARY * 0.10 AS NEWSALARY FROM EMPLOYEE
ORDER BY NEWSALARY
```

## 10.

```{sql connection=con}
SELECT ENO, ENAME, SALARY AS OLDSALARY, SALARY + SALARY * 0.10 AS NEWSALARY FROM EMPLOYEE
WHERE NEWSALARY > 2000.0
ORDER BY NEWSALARY
```

## 11.

```{sql connection=con}
SELECT SUM(SALARY) AS SOMA, AVG(SALARY) AS MEDIA, MAX(SALARY) AS MAX, MIN(SALARY) AS MIN FROM EMPLOYEE
```

## 12.

```{sql connection=con}
SELECT COUNT(DNO) FROM EMPLOYEE
WHERE DNO = '20'
```

## 13.

```{sql connection=con}
SELECT COUNT(DISTINCT DNO) FROM EMPLOYEE
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
